# Copyright 2024 Michael F. Collins, III
#
# Building Microservices with Dapr © 2024 by Michael F. Collins, III is
# licensed under CC BY-ND 4.0. To view a copy of this license, visit
# https://creativecommons.org/licenses/by-nd/4.0/

[book]
authors = ["Michael Collins"]
language = "en"
multilingual = false
src = "src"
title = "Building Microservices with Dapr"

[output.html]

[output.epub]

[output.pdf]
