# Copyright 2024 Michael F. Collins, III
#
# Building Microservices with Dapr © 2024 by Michael F. Collins, III is
# licensed under CC BY-ND 4.0. To view a copy of this license, visit
# https://creativecommons.org/licenses/by-nd/4.0/

FROM mcr.microsoft.com/devcontainers/base:1.0.17-bookworm

RUN apt-get update && apt-get install gnupg2 -y
